<script>
    export default {
        props: {
            experience : Object
        },
        components: {
        },
    
        computed:{
           activeExperience(){
                return this.prevExperience.find(el => el.id === this.experience.id);
           }
        },
        data(){
            return {
                prevExperience : [
                    {
                        id: 1,
                        tools : "PHP Laravel, Vue.js, Sass, Git",
                        description : 'Substantive research is a fin-tech startup which offers wealth managers a saas product to help them benchmark their research and market data payments. I started in the company in 2021 as a software developer and got promoted to mid-level full stack software developer. Working in a small team within a start up means doing more than just developing, such as client feedback, product development and planning, A/B testing with wireframes, UI/UX, and helping ideas grow to full featured products. But when it does come to developing, it means learning and moving fast which our team is great at helping each other out with. Our stack is PHP (Laravel), Javascript (Vue.js). CSS (Sass) and internal with Git, Bitbucket, Jira. While being in the company I helped develop 4 products, upgrade frameworks, build dashboards with data visualisations, build in CI/CD pipeline, test frameworks, and won two awards for best ESG dashboard (one of our products). ',
                        imageFolder: '',
                        imagesTo: 0
                    },
                    {
                        id: 2,
                        tools : "PHP, Laravel, CSS, Vue.js",
                        description: "My major role in the company was being responsible for the technical development. Mela Insights is a web platform for purpose-built venues where they are able to source events which best match their specifications, location, and open calendar dates. I contributed to developing the product from scratch, heading up the design, such as wireframes, all the way through development. Our stack was PHP (laravel), Javascript (Vue,js), CSS (sass) while using Adobe XD for wireframes and prototypes. I too assisted in communication with key users for testing and validation of ideas, including going to international events such as IBTM in Barcelona. While building the company my co-founder and I were listed as the 25 under 25 business woman in Wales. Before the company was formed, I was apart of The Alacrity Foundation, which is a charity organisation that aims to train graduates to become future tech entrepreneurs. During this time, as a technical lead, completed both the tech and business bootcamps that were part of the program. I gained new skills in public speaking, from the numerous panel updates and presentations, team cooperation, from the groups we were placed in, and product validation, from the ideas that were given to us. The biggest thing I learnt was the ins and outs of a business and how each building block in the entrepreneurial process is just as important as the previous one.",
                        imageFolder: 'techdec', 
                        imagesTo: 25 
                    },
                    {
                        id: 3,
                        tools : "PHP, CSS, JS",
                        description : 'Through the years, to keep up to date with my web development skills, I would help out friends and family by creating simple company websites. There was The Clean Machine, a mobile cleaning service based in Johannesburg, South Africa. A small start-up that is planning to move their business forward, wanted a simple website to get awareness out. Just a one page website that gives an overview of what services they can offer their clients. Another was Cherry Tree Cottage, a bed and breakfast in the countryside of Edinburgh. Run by a South African/English couple who added a bit of their heritage throughout the house and wanted that to be portrayed in their website too. It is a simple yet informative website that allows people to have a bit more of a feel of the place before they arrive. Finally my first ever website I created was Boake Incorporated, an accounting firm based in Johannesburg, South Africa. This was my first freelance work where I was able to take a company like Boake Incorporated and promote their online presence. Boake required an uncomplicated but informative website where content was priority but the company culture had to be portrayed through the website too.',
                        imageFolder: 'freelance',
                        imagesTo: 7
                    },
                    {
                        id: 4,
                        tools : "Event planning and management",
                        description : 'iMPAC was founded in 2009. It is a non-profit organisation focused on challenging and enhancing sight-sound thinking and moving-image content generated by students and professionals working in Sub-Saharan Africa. I was fortunate to be part of the team that organised this event at the Open Window Institute for it’s 5th iteration. My role was ensuring that there was enough artists, films and installations for each day. I too help artists get to the venue and back as well as making sure that films and installations started on time.',
                        imageFolder: 'impac',
                        imagesTo: 19
                    },
    
                ],
                activeRoleID : 1,
                showMore : false,
            }
        },
        methods:{
            changeCurrentRole(newId){
                this.activeRoleID = newId;
            },
            handleFocusOut(){
                this.showMore = false;
            },
            getImage(imageName){
                return new URL(`../../assets/images/experience/${imageName}`, import.meta.url).href;
            },

        }
    }
</script>
<template>
  <div class="exp__see-more-info" v-if="activeExperience">
    <!-- Left Side -->
    <div class="see-more__left">
        <div class="heading__two">
            From {{experience.yearFrom}} -  {{experience.yearTo}}
        </div>
        <div class="heading__six">{{experience.role}}</div>
        <div class="heading__five">Tools: {{activeExperience.tools}}</div>
        <div class="description">{{activeExperience.description}}</div>
    </div>

    <!-- Rigth Side -->
    <div class="see-more__right" v-if="activeExperience.imageFolder">
        <div class="left__images" >
            <img v-for="index in activeExperience.imagesTo" 
            :key="index" 
            :src="getImage(activeExperience.imageFolder + '/img'+(index-1)+'.jpg')" />
        </div> 
    </div>
  </div>
</template>